version: "3.7"

services:
  codeserver:
    image: vkhurana/vscode-server-dotnetcore-arm64v8
    container_name: vscode-server-dotnetcore-test
    hostname: vscode-server-dotnetcore-host
    domainname: foo.bar
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Los_Angeles
      - SUDO_PASSWORD=password
    build: .
    volumes:
      - ./.mount/config:/config
    restart: unless-stopped
    network_mode: host
    ports:
      - 8443:8443